server:
  port: 1011

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: ENC(rC/X/8UBBH2bn9Tgfuu7aw==)
    password: ENC(rC/X/8UBBH2bn9Tgfuu7aw==)
    url: jdbc:mysql://localhost:3306/fw-cloud?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false

zipkin:
  collector:
    rabbitmq:
      addresses: 127.0.0.1:5672
      password: guest
      username: guest
      queue: zipkin
  storage:
    type: mysql
